# Dockerfile.api
FROM python:3.9-slim

ENV PYTHONUNBUFFERED=1
ENV USER_AGENT="Mozilla/5.0 (compatible; GenAIColdEmailBot/1.0; +http://yourdomain.com)"
ENV PYTHONPATH=/app

WORKDIR /app

# Use explicit relative path
COPY ./requirements.txt .

RUN pip install --upgrade pip && pip install -r requirements.txt && rm -rf /root/.cache/pip

# Copy the rest of the repository
COPY . .

EXPOSE 8080

CMD ["uvicorn", "src/api/app:app", "--host", "0.0.0.0", "--port", "8080"]
