name: Docker Build and Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Clean up Docker resources
        run: docker system prune -af

      - name: Build Docker images using Docker Compose
        run: docker compose -f docker-compose.yml build

      - name: Start containers with Docker Compose
        run: |
          docker compose -f docker-compose.yml up -d
          sleep 15  # Wait for containers to start

      - name: Test API endpoint
        run: |
          curl --fail http://localhost:8080/ || exit 1

      - name: Shut down containers
        run: docker compose -f docker-compose.yml down
