name: Docker Build and Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

<<<<<<< HEAD
      - name: Clean up Docker resources
        run: docker system prune -af
=======
      - name: Build Docker images using docker-compose
        run: docker compose -f docker-compose.yml build
>>>>>>> c032f07 (Your commit message)

      - name: Build Docker images using Docker Compose
        run: docker compose -f docker-compose.yml build

      - name: Start containers with Docker Compose
        run: |
          docker compose -f docker-compose.yml up -d
          sleep 15  # Wait for containers to start

      - name: Test API endpoint
        run: |
          curl --fail http://localhost:8080/ || exit 1

      - name: Shut down containers
<<<<<<< HEAD
        run: docker compose -f docker-compose.yml down
=======
        run: docker-compose -f docker-compose.yml down

      - name: Clean up disk space
        run: sudo rm -rf /tmp/*
>>>>>>> c032f07 (Your commit message)
